export const SET_SINGER = "SET_SINGER"

export const SET_PLAYING = "SET_PLAYING"

export const SET_FULLSCREEN = "SET_FULLSCREEN"

export const SET_PLAYLIST = "SET_PLAYLIST"

export const SET_SEQUENCELIST = "SET_SEQUENCELIST"

export const SET_PLAYMODE = "SET_PLAYMODE"

export const SET_CURRENTINDEX = "SET_CURRENTINDEX"

export const DELETE_PLAYLIST = "DELETE_PLAYLIST"

export const DELETE_SEQUENCELIST = "DELETE_SEQUENCELIST"

export const SET_PLAYER = "SET_PLAYER"

export const SET_RANKBAR = "SET_RANKBAR"

export const ADD_SONG = "ADD_SONG"

export const SAVE_SEARCHHISTORY = "SAVE_SEARCHHISTORY"

export const CLEAR_SEARCHHISTORY = "CLEAR_SEARCHHISTORY"

export const NEXT_PLAY = "NEXT_PLAY"

export const ADD_FAVORITE = "ADD_FAVORITE"

export const DELETE_FAVORITE = "DELETE_FAVORITE"

export const REFRESH_FAVORITE = "REFRESH_FAVORITE"

export const REFRESH_MYALBUM = "REFRESH_MYALBUM"

export const REFRESH_COLLECTALBUM = "REFRESH_COLLECTALBUM"


